// packages/playground/vue-vite-demo/src/App.vue
<script lang="ts" setup>
import { useFileHashInfo } from './hooks/useFileHashInfo'
import { benchmark, BenchmarkOptions } from 'hash-worker-benchmark'

const { handleInputChange, handleGetHash, handleDestroyWorkerPool } = useFileHashInfo()

function handleDoBenchmark() {
  const options: BenchmarkOptions = {}
  benchmark(options).then(() => {
  })
}

</script>

<template>
  <div>Hello</div>
  <input type="file" @change="handleInputChange" />

  <div>
    <button @click="handleGetHash">get Hash</button>
    <button @click="handleDestroyWorkerPool">destroy pool</button>
    <button @click="handleDoBenchmark">Benchmark</button>
  </div>
</template>

// packages/playground/react-webpack-demo/src/app.tsx
import React from 'react'
import { getFileHashChunks, HashChksRes, HashChksParam } from 'hash-worker'

const App: React.FC = () => {
  let file: File

  function handleInputChange(e: any) {
    file = e.target.files[0]
  }

  function handleGetHash() {
    const param: HashChksParam = {
      file: file!,
      config: {
        workerCount: 8,
      },
    }

    getFileHashChunks(param).then((data: HashChksRes) => {
      console.log(data)
    })
  }

  return (
    <>
      <div>Hello</div>
      <input type="file" onChange={ handleInputChange } />
      <button onClick={ handleGetHash }>get Hash</button>
    </>
  )
}

export default App
