// packages/playground/src/App.vue
<script lang="ts" setup>
import { ref } from 'vue'
import { getFileHashChunks, Strategy, FileHashChunksResult } from 'kun-hash'

const file = ref()

function handleInputChange(e: any) {
  file.value = e.target.files[0]
}

function handleGetHash() {
  getFileHashChunks({
    file: file.value,
    strategy: Strategy.crc32
  }).then((data: FileHashChunksResult) => {
    console.log('chunksHash', data.chunksHash)
  })
}

</script>

<template>
  <div>Hello</div>
  <input ref="inputRef" type="file" @change="handleInputChange"/>
  <button @click="handleGetHash">get Hash</button>
</template>

<style scoped>
</style>

// packages/playground/react-webpack-demo/src/app.tsx
import React from 'react'
import { getFileHashChunks, HashChksRes, HashChksParam } from 'hash-worker'

const App: React.FC = () => {
  let file: File

  function handleInputChange(e: any) {
    file = e.target.files[0]
  }

  function handleGetHash() {
    const param: HashChksParam = {
      file: file!,
      config: {
        workerCount: 8,
      },
    }

    getFileHashChunks(param).then((data: HashChksRes) => {
      console.log(data)
    })
  }

  return (
    <>
      <div>Hello</div>
      <input type="file" onChange={ handleInputChange } />
      <button onClick={ handleGetHash }>get Hash</button>
    </>
  )
}

export default App
