// packages/playground/react-rsbuild-demo/src/App.tsx
import React, { useCallback, useRef } from 'react'
import { getFileHashChunks, HashWorkerOptions, HashWorkerResult, Strategy } from 'hash-worker'

const App = () => {
  const fileRef = useRef<File | null>(null)

  const handleInputChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.currentTarget.files
    if (files?.[0]) {
      fileRef.current = files[0]
    }
  }, [])

  const handleGetHash = useCallback(() => {
    const param: HashWorkerOptions = {
      file: fileRef.current!,
      config: {
        workerCount: 6,
        strategy: Strategy.md5,
        isShowLog: true,
      },
    }

    getFileHashChunks(param).then((data: HashWorkerResult) => {
      console.log(data)
      alert('Calculation complete, please check the console!')
    })
  }, [])

  return (
    <>
      <div>Hello</div>
      <input type="file" onChange={handleInputChange} />
      <button onClick={handleGetHash}>get Hash</button>
    </>
  )
}

export default App

// packages/playground/vue-demo/src/App.vue
<script lang="ts" setup>
import { ref } from 'vue'
import { getFileHashChunks, Strategy, FileHashChunksResult, FileHashChunksParam } from 'kun-hash'

const file = ref<File>()

function handleInputChange(e: any) {
  file.value = e.target.files[0]
}

function handleGetHash() {
  const param: FileHashChunksParam = {
    file: file.value!,
    strategy: Strategy.crc32
  }

  getFileHashChunks(param).then((data: FileHashChunksResult) => {
    console.log('chunksHash', data.chunksHash)
  })
}

</script>

<template>
  <div>Hello</div>
  <input type="file" @change="handleInputChange"/>
  <button @click="handleGetHash">get Hash</button>
</template>

<style scoped>
</style>
