// packages/playground/react-webpack-demo/src/app.tsx
import React from 'react'
import { getFileHashChunks, HashChksRes, HashChksParam } from 'hash-worker'

const App: React.FC = () => {
  let file: File

  function handleInputChange(e: any) {
    file = e.target.files[0]
  }

  function handleGetHash() {
    const param: HashChksParam = {
      file: file!,
      config: {
        workerCount: 8,
      },
    }

    getFileHashChunks(param).then((data: HashChksRes) => {
      console.log(data)
    })
  }

  return (
    <>
      <div>Hello</div>
      <input type="file" onChange={ handleInputChange } />
      <button onClick={ handleGetHash }>get Hash</button>
    </>
  )
}

export default App

// packages/playground/vue-demo/src/App.vue
<script lang="ts" setup>
import { ref } from 'vue'
import { getFileHashChunks, destroyWorkerPool, HashChksRes, HashChksParam } from 'hash-worker'

const file = ref<File>()

function handleInputChange(e: any) {
  file.value = e.target.files[0]
}

function handleGetHash() {
  const param: HashChksParam = {
    file: file.value,
    config: {
      maxWorkerCount: 2
    }
  }

  const beforeDate = Date.now()
  getFileHashChunks(param).then((data: HashChksRes) => {
    const afterDate = Date.now()
    console.log(data)
    console.log(afterDate - beforeDate)
  })
}

/**
 * Destroy Worker Thread
 */
function handleDestroyWorkerPool() {
  destroyWorkerPool()
}

</script>

<template>
  <div>Hello</div>
  <input type="file" @change="handleInputChange"/>
  <button @click="handleGetHash">get Hash</button>
  <button @click="handleDestroyWorkerPool">destroy pool</button>
</template>

<style scoped>
</style>
